language: node_js
node_js:
  - "4.1"

sudo: required
dist: trusty

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.0.5 mongodb-org-server=3.0.5 mongodb-org-shell=3.0.5 mongodb-org-mongos=3.0.5 mongodb-org-tools=3.0.5

before_script:
  - sudo service mongod status
  - sudo apt-get update -qq
  - sudo apt-get install -y libicu52 libjpeg8 libfontconfig libwebp5
  - npm install -g gulp
  - npm install -g jasmine-node
  - cd server
  - npm install
  - cd ..
  - rvm 2.2.3
  - gem install scss_lint
  - bash setup.sh

script:
  - bash test/test.sh

after_script:
  - cat nohup.out

addons:
  code_climate:
    repo_token: 4b9bad2eb36ad49fa1af9b04b49cf4e068dcb6086a5e216fccf988221479118a
